### ISSUE TITLE
About Version Number

### ISSUE THREAD

**Issue by PurpleNoon** [asledgehammer/PipeWrench#46]
The current version number changes with the game version and does not have its own version number. Do you have any ideas about changing the version number? For example:

```jsonc
{
  // before
  "version": "41.78.16",
  // after
  "version": "41001.78001.16001",
}
```

Version 41001.78001.16001 indicates that the game version is v41.78.16, and the current repository version is v1.1.1.

This can more conveniently reflect the changes in the warehouse.

**Comment by JabDoesThings** [comment]
For build 42 forward, I'll probably be doing PZ-Version-PipeWrench-Revision.
E.G:
`42.0.0-1` for Revision 1 of version `41.0.0`.
