### ISSUE TITLE
Automatic release to npm on tags

### ISSUE THREAD

**Issue by shughes-uk** [asledgehammer/PipeWrench#6]
Messing around and I think it would be beneficial to release this to npm automatically via tags using github actions. 

## Why

The compiler/template can then depend on specific versions depending on what the mod is targeting. Or multiple if needed. I'd actually like to split the compile into it's own cli app , which could depend on all versions and target each one as needed, much like tsc does with ES versions.

## Versioning

I propose package versions should approximate the PZ version the type stubs are generated for.

Going with just standard semver you'd release `0.41.71`, `0.41.73` ect. I'm not sure this is ideal given that patches are inevitable and npm does not allow post-release versions like pypi.

So I suggest `041.71.0`. If PZ bumps a major release version we append it to the major version number ie  `141.71.0`. 

## Naming

pipe-wrench is an existing package so pipewrench is a no go, I'd suggest @asledgehammer/pipewrench

## Notes

I'm happy to take on this but some stuff (npm credentials) will probably need to be figured out

**Comment by Konijima** [comment]
So we have a stable and unstable branch that always follow the latest pz stable and unstable branch. And when pz move an unstable to the stable branch we just save a branch of that previous stable version.

A npm module with versioning is good for sure, not against it but I personally just need stable and unstable branch for my mod development so I didn't bother with npm.

On the other hand I think @JabDoesThings should be making the npm module and add contributors to allow for publishing updates if he decides to go with npm modules.

For now we simply includes repo url into package.json and specify a branch if needed.
```json
  "dependencies": {
    "PipeWrench": "github:asledgehammer/PipeWrench#stable",
    "PipeWrench-Events": "github:asledgehammer/PipeWrench-Events",
    "PipeWrench-Utils": "github:asledgehammer/PipeWrench-Utils"
  },
```

**Comment by shughes-uk** [comment]
I think the disadvantage of that is that it excludes mod developers from supporting legacy versions, while still having 'latest' versions of the compiler (lots of MP servers with heavily customized mods need to do this)

It also makes it harder to reason about what API version you're looking at, stable/unstable both change while the version numbers are relatively immutable (unstable builds flex a bit but that's what the patch releases will be handy for)
